### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by singhh9596** [jtvpremium/jio-jtv-premium#18]
Can you please cut down the app size for Android TV. It's taking toll in the processor.

After installation the app, channels won't load even after waiting for more than 2 minutes. Upon clicking back button the tv lags too much due to it's size.

Using beta version for Android Tv

**Comment by jtvpremium** [comment]
can you provide us tv details for example tv model number or tv name.

**Comment by singhh9596** [comment]
Redmi 43' 4k smartTV

> can you provide us tv details for example tv model number or tv name.

**Comment by digvijay9x** [comment]
> can you provide us tv details for example tv model number or tv name.

Redmi 5a (32 inc) , Android 11

**Comment by techgamers2** [comment]
> Why is the apk size in kbs?

DOWNLOAD IT from readme section >> [download](https://github.com/jtvpremium/jio-jtv-premium?tab=readme-ov-file#download)

**Comment by singhh9596** [comment]
> > Why is the apk size in kbs?
> 
> DOWNLOAD IT from readme section >> [download](https://github.com/jtvpremium/jio-jtv-premium?tab=readme-ov-file#download) it will be around 100mb which is pretty big compared to original jiotv app which is around 25mb ..... its not problem but tv stb has less space to begin with
> 
> edit : reason behind big file size is he bundled arm64-v8a,armeabi-v7a,x86_64 together also channel logo images could be compressed further using [Mass Image Compressor](https://sourceforge.net/projects/icompress/)

But android tv version doesn't work. Keeps on loading but never plays even my tv lags upon installing the app. App too heavy

**Comment by techgamers2** [comment]
u can try [JIO TV addon](https://tobalan.github.io/) by @tobalan on [kodi app ](https://kodi.tv/download/)
