### ISSUE TITLE
JTV app not working 

### ISSUE THREAD

**Issue by Apkepapa** [jtvpremium/jio-jtv-premium#2]
JTV APP not working on Android TV

**Comment by Apkepapa** [comment]
Android tv pr kam nhi kr raha .. mobile no. Dalne pr done option pr click nhi hota..

**Comment by jtvpremium** [comment]
Issue fixed download tv version apk

**Comment by Apkepapa** [comment]
Thank you sir for keep in touch.  
The Android JTV app works fantastic. 
Thankyou sir..❣️❣️❣️😇

**Comment by Apkepapa** [comment]
sir... I think there should be a favorite option or category option in Android JTV.
😇
