### ISSUE TITLE
Some icons are not working.

### ISSUE THREAD

**Issue by dacait01** [jtvpremium/jio-jtv-premium#5]
https://drive.google.com/drive/folders/1jEyBX3Pj0I53P_rECepnNLF4pMNA5V-r?usp=sharing

That is G-Drive link there i mention some images from you can understand the problem.

**Comment by AMEET82** [comment]
How to login in android TV?
Cannot enter otp

**Comment by mesh17** [comment]
same can't enter OTP on android TV , works with macos, phone ! @jtvpremium

**Comment by jtvpremium** [comment]
issue fixed and download latest
